export type ComponentItem = {
  title: string;
  disabled?: boolean;
};

export const shadcnComponents: ComponentItem[] = [
  { title: "Accordion", disabled: true },
  { title: "Alert", disabled: true },
  { title: "Alert Dialog", disabled: true },
  { title: "Aspect Ratio", disabled: true },
  { title: "Avatar", disabled: true },
  { title: "Badge", disabled: true },
  { title: "Breadcrumb", disabled: true },
  { title: "Button", disabled: true },
  { title: "Calendar", disabled: true },
  { title: "Card", disabled: true },
  { title: "Carousel", disabled: true },
  { title: "Chart", disabled: true },
  { title: "Checkbox", disabled: true },
  { title: "Collapsible", disabled: true },
  { title: "Combobox", disabled: true },
  { title: "Command", disabled: true },
  { title: "Context Menu", disabled: true },
  { title: "Data Table", disabled: true },
  { title: "Date Picker", disabled: true },
  { title: "Dialog", disabled: true },
  { title: "Drawer", disabled: true },
  { title: "Dropdown Menu", disabled: true },
  { title: "Form", disabled: true },
  { title: "Hover Card", disabled: true },
  { title: "Input", disabled: true },
  { title: "Input OTP", disabled: true },
  { title: "Label", disabled: true },
  { title: "Menubar", disabled: true },
  { title: "Navbar", disabled: false },
  { title: "Navigation Menu", disabled: true },
  { title: "Pagination", disabled: true },
  { title: "Popover", disabled: true },
  { title: "Progress", disabled: true },
  { title: "Radio Group", disabled: true },
  { title: "Resizable", disabled: true },
  { title: "Scroll Area", disabled: true },
  { title: "Select", disabled: true },
  { title: "Separator", disabled: true },
  { title: "Sheet", disabled: true },
  { title: "Skeleton", disabled: true },
  { title: "Slider", disabled: true },
  { title: "Sonner", disabled: true },
  { title: "Switch", disabled: true },
  { title: "Table", disabled: true },
  { title: "Tabs", disabled: true },
  { title: "Textarea", disabled: true },
  { title: "Toast", disabled: true },
  { title: "Toggle", disabled: true },
  { title: "Toggle Group", disabled: true },
  { title: "Tooltip", disabled: true },
  { title: "Typography", disabled: true },
];
